package web

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/Maoyangui/m-ui/database/model"
)

// sessionTokenTagLen is the hexadecimal length of a 16-byte credential tag.
// The tag is carried in the token itself so password resets performed by the
// command-line menu can invalidate already persisted sessions too, without
// changing the sessions table schema.
const sessionTokenTagLen = 32

// 0.6.9 起令牌尾部带凭据指纹;更早签发的令牌(64 位十六进制)一律拒绝,升级后已登录的管理员 / 代理要重新登录一次 —— 只此一次,
// 之后升级照旧保持登录(会话落库,进程重启不丢)。

// sessionCredentialTag binds a session to the current credential.  Passwords
// are already one-way hashes here; hashing the stored value again avoids
// putting any credential material in the token while still changing the tag
// whenever the password is changed (bcrypt uses a fresh salt each time).
func sessionCredentialTag(role, identity, password string) string {
	h := sha256.New()
	h.Write([]byte(role))
	h.Write([]byte{0})
	h.Write([]byte(identity))
	h.Write([]byte{0})
	h.Write([]byte(password))
	return hex.EncodeToString(h.Sum(nil)[:sessionTokenTagLen/2])
}

func sessionTokenWithCredential(token, role, identity, password string) string {
	return token + sessionCredentialTag(role, identity, password)
}

func sessionTokenTag(token string) (string, bool) {
	// The random portion generated by newSession/newResellerSession is 32
	// bytes (64 hex characters).  Reject old-format tokens so sessions created
	// before credential binding are required to log in again after upgrading.
	if len(token) != 64+sessionTokenTagLen {
		return "", false
	}
	if _, err := hex.DecodeString(token); err != nil {
		return "", false
	}
	return token[64:], true
}

// 凭据指纹的短期缓存:每个已登录请求都要核对一次令牌里的指纹,不缓存就是每个请求多一次 SQLite 读。
// 缓存几秒足够 —— 改密码的路径都会显式清掉(invalidate*Sessions),CLI / 菜单里改的密码最多晚几秒生效。
var credCacheTTL = 3 * time.Second // 测试里会清零

type credEntry struct {
	tag string
	at  time.Time
}

var (
	credCacheMu sync.Mutex
	credCache   = map[string]credEntry{}
)

// expectedCredentialTag 当前库里该账号的凭据指纹;查不到返回空串。带 TTL 缓存。
func (s *Server) expectedCredentialTag(role, key string, load func() (identity, password string, ok bool)) string {
	ck := fmt.Sprintf("%p|%s|%s", s, role, key)
	credCacheMu.Lock()
	if e, ok := credCache[ck]; ok && time.Since(e.at) < credCacheTTL {
		credCacheMu.Unlock()
		return e.tag
	}
	credCacheMu.Unlock()
	identity, password, ok := load()
	if !ok {
		return ""
	}
	tag := sessionCredentialTag(role, identity, password)
	credCacheMu.Lock()
	credCache[ck] = credEntry{tag: tag, at: time.Now()}
	credCacheMu.Unlock()
	return tag
}

// forgetCredentialTags 改密码 / 重置之后清掉这台 Server 的缓存,新指纹立刻生效。
func (s *Server) forgetCredentialTags() {
	prefix := fmt.Sprintf("%p|", s)
	credCacheMu.Lock()
	for k := range credCache {
		if strings.HasPrefix(k, prefix) {
			delete(credCache, k)
		}
	}
	credCacheMu.Unlock()
}

func (s *Server) sessionCredentialValid(token string, sess session) bool {
	tag, ok := sessionTokenTag(token)
	if !ok {
		return false
	}
	if sess.reseller > 0 {
		expected := s.expectedCredentialTag("reseller", strconv.FormatUint(uint64(sess.reseller), 10), func() (string, string, bool) {
			var rs model.Reseller
			if s.db == nil || s.db.First(&rs, sess.reseller).Error != nil {
				return "", "", false
			}
			return strconv.FormatUint(uint64(rs.Id), 10), rs.Password, true
		})
		return expected != "" && subtle.ConstantTimeCompare([]byte(tag), []byte(expected)) == 1
	}
	if s.db != nil {
		expected := s.expectedCredentialTag("admin", sess.user, func() (string, string, bool) {
			var admin model.Admin
			if s.db.Where("username = ?", sess.user).First(&admin).Error != nil {
				return "", "", false
			}
			return strconv.FormatUint(uint64(admin.Id), 10), admin.Password, true
		})
		if expected != "" {
			return subtle.ConstantTimeCompare([]byte(tag), []byte(expected)) == 1
		}
	}
	// A Server used by a small unit test may not have an Admin row.  The real
	// server always creates one during startup; retaining a deterministic tag
	// here keeps those in-memory session tests meaningful without accepting old
	// untagged sessions.
	expected := sessionCredentialTag("admin", sess.user, "")
	return subtle.ConstantTimeCompare([]byte(tag), []byte(expected)) == 1
}

// 会话:内存 map 是缓存,库里的 sessions 表是事实。登录写库,校验先看缓存、没有再查库,
// 登出与过期从两边删。这样一键更新、重启、菜单里重启之后,管理员和代理都还在登录状态。

func (s *Server) putSession(token string, sess session) {
	s.mu.Lock()
	if s.sessions == nil {
		s.sessions = map[string]session{}
	}
	s.sessions[token] = sess
	s.mu.Unlock()
	if s.db != nil {
		s.db.Save(&model.Session{Token: token, User: sess.user, Reseller: sess.reseller, Pending: sess.pending, Exp: sess.exp.Unix()})
	}
}

// getSession 取会话;过期的顺手删掉。
func (s *Server) getSession(token string) (session, bool) {
	if token == "" {
		return session{}, false
	}
	s.mu.Lock()
	sess, ok := s.sessions[token]
	s.mu.Unlock()
	if !ok && s.db != nil {
		var row model.Session
		if err := s.db.Where("token = ?", token).First(&row).Error; err == nil {
			sess = session{user: row.User, reseller: row.Reseller, pending: row.Pending, exp: time.Unix(row.Exp, 0)}
			ok = true
			s.mu.Lock()
			if s.sessions == nil {
				s.sessions = map[string]session{}
			}
			s.sessions[token] = sess
			s.mu.Unlock()
		}
	}
	if !ok {
		return session{}, false
	}
	if time.Now().After(sess.exp) {
		s.delSession(token)
		return session{}, false
	}
	return sess, true
}

func (s *Server) delSession(token string) {
	s.mu.Lock()
	delete(s.sessions, token)
	s.mu.Unlock()
	if s.db != nil {
		s.db.Where("token = ?", token).Delete(&model.Session{})
	}
}

// invalidateResellerSessions revokes every browser session for a reseller.
// Both stores are cleared because the in-memory map is a hot cache while the
// database is shared across restarts and between the two panel listeners.
func (s *Server) invalidateResellerSessions(id uint) {
	s.forgetCredentialTags()
	s.mu.Lock()
	for token, sess := range s.sessions {
		if sess.reseller == id {
			delete(s.sessions, token)
		}
	}
	s.mu.Unlock()
	if s.db != nil {
		s.db.Where("reseller = ?", id).Delete(&model.Session{})
	}
}

// invalidateAdminSessions revokes all sessions for the administrator whose
// password is being changed.  It intentionally uses the previous username:
// a password change may also rename the account, and all pre-change sessions
// still carry the old name.
func (s *Server) invalidateAdminSessions(username string) {
	s.forgetCredentialTags()
	s.mu.Lock()
	for token, sess := range s.sessions {
		if sess.reseller == 0 && sess.user == username {
			delete(s.sessions, token)
		}
	}
	s.mu.Unlock()
	if s.db != nil {
		s.db.Where("reseller = ? AND user = ?", 0, username).Delete(&model.Session{})
	}
}

// updateSession 改一个会话的字段(代理设完密码后清掉待设标记)。
func (s *Server) updateSession(token string, fn func(*session)) {
	sess, ok := s.getSession(token)
	if !ok {
		return
	}
	fn(&sess)
	s.putSession(token, sess)
}
